name: CI/CD Workflow

on:
  push:          # Triggers on push events (to any branch)
    branches:
      - '**'     # Matches all branches (you can also use '*' for all branches)
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      BASE_DIR: /root
      PROJECT: esp32-freeRTOS2
      APP: demo
      BUILD: dev
      CONTAINER: deploy-freertos
      CONTAINERTAG: freertos

    steps:
    - name: Set Project
      run: echo "Using project $PROJECT"

    - name: Check release tag format
      run: |
        echo "Creating prod release"
        echo "Setting BUILD to prod"
        echo "BUILD=prod" >> $GITHUB_ENV  # Set BUILD environment variable for subsequent steps
      if: github.event_name == 'release'  # Run only on release events

    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Build Docker image
      run: |
        docker build \
        -f Dockerfile \
        --build-arg BASE_DIR=${BASE_DIR} \
        --build-arg PROJECT=${PROJECT} \
        --build-arg APP=${APP} \
        --build-arg BUILD=${BUILD} \
        -t $CONTAINERTAG .

    - name: Run script inside Docker container
      run: |
        docker run --name $CONTAINER $CONTAINERTAG
        docker cp ${CONTAINER}:${PROJECT}/images/ ./images/

    - uses: actions/upload-artifact@v4
      with:
        name: upload images
        path: ./images
        
    - name: Update Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./images/*
        token: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release'  # Run only on release events

    - name: Clean up
      run: |
        docker rm $CONTAINER